name: Connect to Server Using Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Connect to Server with Password
        run: |
          sshpass -p "!!GH#31YuxF" ssh -o StrictHostKeyChecking=no user01@213.233.184.231 "echo 'Server is up!'"
        env:
          SERVER_PASSWORD: "!!GH#31YuxF"
